name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: mkdir build
    - name: cmake build
      run: cmake -B build -H .
    - name: cmake make
      run: cmake --build build/ --target all
    - name: Execute tests
      run: cd build/test && ./NorthStar_test
